-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["filters"] = {
		[1] = "";
		[2] = "";
		[3] = "";
		[4] = "";
		[5] = "";
	};
	["skills"] = {
		[1] = {
			["alias"] = "";
			["collraritylt"] = 0;
			["collrarityltpct"] = 0;
			["collweareq"] = 0;
			["collweargt"] = 0;
			["collwearlt"] = 0;
			["collwearltpct"] = 0;
			["gatherattempts"] = 4;
			["gatherattemptsmax"] = 0;
			["gpbuff"] = "";
			["gpmax"] = 0;
			["gpmin"] = 0;
			["gpnbuff"] = "";
			["gsecspassed"] = 0;
			["hasitem"] = "";
			["id"] = 234;
			["isitem"] = "Fire Cluster";
			["isunspoiled"] = "0";
			["itemchancemax"] = 0;
			["itemhqchancemin"] = 0;
			["lastcast"] = 0;
			["lastcastunique"] = {
			};
			["name"] = "Nald'thal's Ward";
			["prio"] = 1;
			["pskillg"] = "";
			["singleuseonly"] = "1";
			["type"] = 1;
			["used"] = "1";
		};
		[2] = {
			["alias"] = "";
			["collraritylt"] = 0;
			["collrarityltpct"] = 0;
			["collweareq"] = 0;
			["collweargt"] = 0;
			["collwearlt"] = 0;
			["collwearltpct"] = 0;
			["gatherattempts"] = 4;
			["gatherattemptsmax"] = 0;
			["gpbuff"] = "";
			["gpmax"] = 0;
			["gpmin"] = 0;
			["gpnbuff"] = "";
			["gsecspassed"] = 0;
			["hasitem"] = "";
			["id"] = 293;
			["isitem"] = "Water Cluster";
			["isunspoiled"] = "0";
			["itemchancemax"] = 0;
			["itemhqchancemin"] = 0;
			["lastcast"] = 0;
			["lastcastunique"] = {
			};
			["name"] = "Thaliak's Ward";
			["prio"] = 2;
			["pskillg"] = "";
			["singleuseonly"] = "1";
			["type"] = 1;
			["used"] = "1";
		};
		[3] = {
			["alias"] = "";
			["collraritylt"] = 0;
			["collrarityltpct"] = 0;
			["collweareq"] = 0;
			["collweargt"] = 0;
			["collwearlt"] = 0;
			["collwearltpct"] = 0;
			["gatherattempts"] = 4;
			["gatherattemptsmax"] = 0;
			["gpbuff"] = "";
			["gpmax"] = 0;
			["gpmin"] = 0;
			["gpnbuff"] = "";
			["gsecspassed"] = 0;
			["hasitem"] = "";
			["id"] = 219;
			["isitem"] = "Lightning Cluster";
			["isunspoiled"] = "0";
			["itemchancemax"] = 0;
			["itemhqchancemin"] = 0;
			["lastcast"] = 0;
			["lastcastunique"] = {
			};
			["name"] = "Byregot's Ward";
			["prio"] = 3;
			["pskillg"] = "";
			["singleuseonly"] = "1";
			["type"] = 1;
			["used"] = "1";
		};
		[4] = {
			["alias"] = "";
			["collraritylt"] = 0;
			["collrarityltpct"] = 0;
			["collweareq"] = 0;
			["collweargt"] = 0;
			["collwearlt"] = 0;
			["collwearltpct"] = 0;
			["gatherattempts"] = 4;
			["gatherattemptsmax"] = 0;
			["gpbuff"] = "";
			["gpmax"] = 0;
			["gpmin"] = 0;
			["gpnbuff"] = "";
			["gsecspassed"] = 0;
			["hasitem"] = "";
			["id"] = 236;
			["isitem"] = "Ice Cluster";
			["isunspoiled"] = "0";
			["itemchancemax"] = 0;
			["itemhqchancemin"] = 0;
			["lastcast"] = 0;
			["lastcastunique"] = {
			};
			["name"] = "Menphina's Ward";
			["prio"] = 4;
			["pskillg"] = "";
			["singleuseonly"] = "1";
			["type"] = 1;
			["used"] = "1";
		};
		[5] = {
			["alias"] = "";
			["collraritylt"] = 0;
			["collrarityltpct"] = 0;
			["collweareq"] = 0;
			["collweargt"] = 0;
			["collwearlt"] = 0;
			["collwearltpct"] = 0;
			["gatherattempts"] = 4;
			["gatherattemptsmax"] = 0;
			["gpbuff"] = "";
			["gpmax"] = 0;
			["gpmin"] = 0;
			["gpnbuff"] = "";
			["gsecspassed"] = 0;
			["hasitem"] = "";
			["id"] = 217;
			["isitem"] = "Earth Cluster";
			["isunspoiled"] = "0";
			["itemchancemax"] = 0;
			["itemhqchancemin"] = 0;
			["lastcast"] = 0;
			["lastcastunique"] = {
			};
			["name"] = "Nophica's Ward";
			["prio"] = 5;
			["pskillg"] = "";
			["singleuseonly"] = "1";
			["type"] = 1;
			["used"] = "1";
		};
		[6] = {
			["alias"] = "";
			["collraritylt"] = 0;
			["collrarityltpct"] = 0;
			["collweareq"] = 0;
			["collweargt"] = 0;
			["collwearlt"] = 0;
			["collwearltpct"] = 0;
			["gatherattempts"] = 4;
			["gatherattemptsmax"] = 0;
			["gpbuff"] = "";
			["gpmax"] = 0;
			["gpmin"] = 0;
			["gpnbuff"] = "";
			["gsecspassed"] = 0;
			["hasitem"] = "";
			["id"] = 292;
			["isitem"] = "Wind Cluster";
			["isunspoiled"] = "0";
			["itemchancemax"] = 0;
			["itemhqchancemin"] = 0;
			["lastcast"] = 0;
			["lastcastunique"] = {
			};
			["name"] = "Llymlaen's Ward";
			["prio"] = 6;
			["pskillg"] = "";
			["singleuseonly"] = "1";
			["type"] = 1;
			["used"] = "1";
		};
	};
	["version"] = 2;
}
return obj1
