-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["classes"] = {
		[1] = false;
		[2] = false;
		[3] = false;
		[4] = false;
		[5] = false;
		[6] = false;
		[7] = false;
		[8] = false;
		[9] = false;
		[10] = false;
		[11] = false;
		[12] = false;
		[13] = false;
		[14] = false;
		[15] = false;
		[16] = false;
		[17] = false;
		[18] = false;
		[19] = false;
		[20] = false;
		[21] = false;
		[22] = false;
		[23] = false;
		[24] = false;
		[25] = false;
		[26] = false;
		[27] = false;
		[28] = false;
		[29] = false;
		[30] = false;
		[31] = true;
		[32] = false;
		[33] = false;
		[34] = false;
		[35] = false;
	};
	["filters"] = {
		[1] = "Gause On/Off";
		[2] = "AOE On/Off";
		[3] = "Opener Disable";
		[4] = "";
		[5] = "";
	};
	["skills"] = {
		[1] = {
			["alias"] = "Gauss on";
			["combat"] = "Any";
			["gauge3or"] = "0";
			["gcd"] = "False";
			["id"] = 2880;
			["ignoremoving"] = true;
			["levelmin"] = 52;
			["maxRange"] = 0;
			["name"] = "Gauss Barrel";
			["playerlevelmin"] = 52;
			["prio"] = 1;
			["trg"] = "Player";
		};
		[2] = {
			["alias"] = "----- AOE -----";
			["gcdtime"] = 0.5;
			["id"] = 225;
			["prio"] = 2;
		};
		[3] = {
			["alias"] = "Spread Shot - AOE";
			["filtertwo"] = "Off";
			["gcdtime"] = 0.5;
			["id"] = 2870;
			["ignoremoving"] = true;
			["levelmin"] = 18;
			["maxRange"] = 12;
			["name"] = "Spread Shot";
			["playerlevelmin"] = 18;
			["prio"] = 3;
			["tarange"] = 8;
			["tecount"] = 3;
			["terange"] = 8;
		};
		[4] = {
			["alias"] = "----- Single Target -----";
			["gcdtime"] = 0.5;
			["maxRange"] = 25;
			["prio"] = 4;
		};
		[5] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 2872;
			["ignoremoving"] = true;
			["levelmin"] = 30;
			["maxRange"] = 25;
			["name"] = "Hot Shot";
			["playerlevelmin"] = 30;
			["pnbuff"] = "855";
			["pnbuffdura"] = 6;
			["prio"] = 5;
			["secspassed"] = 5;
		};
		[6] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 2869;
			["ignoremoving"] = true;
			["levelmin"] = 6;
			["maxRange"] = 25;
			["name"] = "Lead Shot";
			["prio"] = 6;
			["secspassed"] = 5;
			["tnbuff"] = "854";
			["tnbuffdura"] = 6;
		};
		[7] = {
			["gcdtime"] = 0.5;
			["id"] = 2875;
			["ignoremoving"] = true;
			["levelmin"] = 8;
			["maxRange"] = 25;
			["name"] = "Heartbreak";
			["playerlevelmin"] = 6;
			["prio"] = 7;
		};
		[8] = {
			["id"] = 7413;
			["ignoremoving"] = true;
			["maxRange"] = 25;
			["name"] = "Heated Clean Shot";
			["pbuff"] = "857";
			["prio"] = 8;
		};
		[9] = {
			["id"] = 7412;
			["ignoremoving"] = true;
			["maxRange"] = 25;
			["name"] = "Heated Slug Shot";
			["pbuff"] = "856";
			["prio"] = 9;
		};
		[10] = {
			["id"] = 7411;
			["ignoremoving"] = true;
			["maxRange"] = 25;
			["name"] = "Heated Split Shot";
			["prio"] = 10;
		};
		[11] = {
			["gcdtime"] = 0.5;
			["id"] = 2873;
			["ignoremoving"] = true;
			["levelmin"] = 35;
			["maxRange"] = 25;
			["name"] = "Clean Shot";
			["pbuff"] = "857";
			["playerlevelmin"] = 35;
			["prio"] = 11;
		};
		[12] = {
			["gcdtime"] = 0.5;
			["id"] = 2868;
			["ignoremoving"] = true;
			["levelmin"] = 2;
			["maxRange"] = 25;
			["name"] = "Slug Shot";
			["pbuff"] = "856";
			["playerlevelmin"] = 2;
			["prio"] = 12;
		};
		[13] = {
			["gcdtime"] = 0.5;
			["id"] = 2866;
			["ignoremoving"] = true;
			["levelmin"] = 1;
			["maxRange"] = 25;
			["name"] = "Split Shot";
			["playerlevelmin"] = 1;
			["prio"] = 13;
		};
		[14] = {
			["alias"] = "----- oGCD -----";
			["gcdtime"] = 0.5;
			["maxRange"] = 25;
			["prio"] = 14;
		};
		[15] = {
			["id"] = 7541;
			["ignoremoving"] = true;
			["levelmin"] = 8;
			["maxRange"] = 0;
			["name"] = "Second Wind";
			["phpb"] = 50;
			["playerlevelmin"] = 8;
			["prio"] = 15;
			["trg"] = "Player";
		};
		[16] = {
			["id"] = 7544;
			["ignoremoving"] = true;
			["levelmin"] = 24;
			["maxRange"] = 0;
			["name"] = "Invigorate";
			["playerlevelmin"] = 24;
			["prio"] = 16;
			["ptpb"] = 550;
			["trg"] = "Player";
		};
		[17] = {
			["dobuff"] = true;
			["gauge2lt"] = 2;
			["gcdtime"] = 0.5;
			["id"] = 2879;
			["ignoremoving"] = true;
			["levelmin"] = 38;
			["maxRange"] = 0;
			["name"] = "Quick Reload";
			["playerlevelmin"] = 26;
			["prio"] = 17;
			["trg"] = "Player";
		};
		[18] = {
			["alias"] = "Quick Reload <38";
			["dobuff"] = true;
			["gauge2lt"] = 2;
			["gcdtime"] = 0.5;
			["id"] = 2879;
			["ignoremoving"] = true;
			["levelmax"] = 37;
			["levelmin"] = 26;
			["maxRange"] = 0;
			["name"] = "Quick Reload";
			["playerlevelmin"] = 26;
			["prio"] = 18;
			["trg"] = "Player";
		};
		[19] = {
			["dobuff"] = true;
			["gauge2lt"] = 1;
			["gcdtime"] = 0.5;
			["id"] = 2867;
			["ignoremoving"] = true;
			["levelmin"] = 38;
			["maxRange"] = 0;
			["name"] = "Reload";
			["playerlevelmin"] = 4;
			["prio"] = 19;
			["trg"] = "Player";
		};
		[20] = {
			["alias"] = "Reload <38";
			["dobuff"] = true;
			["gauge2lt"] = 1;
			["gcdtime"] = 0.5;
			["id"] = 2867;
			["ignoremoving"] = true;
			["levelmax"] = 37;
			["levelmin"] = 4;
			["maxRange"] = 0;
			["name"] = "Reload";
			["playerlevelmin"] = 4;
			["prio"] = 20;
			["trg"] = "Player";
		};
		[21] = {
			["gcdtime"] = 0.5;
			["id"] = 2890;
			["ignoremoving"] = true;
			["levelmin"] = 60;
			["maxRange"] = 25;
			["name"] = "Ricochet";
			["playerlevelmin"] = 60;
			["prio"] = 21;
			["tarange"] = 5;
			["terange"] = 5;
		};
		[22] = {
			["gcdtime"] = 0.5;
			["id"] = 2885;
			["ignoremoving"] = true;
			["levelmin"] = 58;
			["maxRange"] = 0;
			["name"] = "Hypercharge";
			["playerlevelmin"] = 58;
			["prio"] = 22;
			["trg"] = "Player";
		};
		[23] = {
			["gcdtime"] = 0.5;
			["id"] = 2874;
			["ignoremoving"] = true;
			["levelmin"] = 54;
			["maxRange"] = 25;
			["name"] = "Gauss Round";
			["playerlevelmin"] = 54;
			["prio"] = 23;
		};
		[24] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 2881;
			["ignoremoving"] = true;
			["levelmin"] = 38;
			["maxRange"] = 0;
			["name"] = "Rapid Fire";
			["playerlevelmin"] = 30;
			["prio"] = 24;
			["trg"] = "Player";
		};
		[25] = {
			["alias"] = "Rapid Fire <38";
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 2881;
			["ignoremoving"] = true;
			["levelmax"] = 37;
			["levelmin"] = 30;
			["maxRange"] = 0;
			["name"] = "Rapid Fire";
			["playerlevelmin"] = 30;
			["prio"] = 25;
			["trg"] = "Player";
		};
		[26] = {
			["dobuff"] = true;
			["gcd"] = "True";
			["gcdtime"] = 0;
			["gcdtimelt"] = 0;
			["id"] = 2876;
			["ignoremoving"] = true;
			["levelmin"] = 38;
			["maxRange"] = 0;
			["name"] = "Reassemble";
			["playerlevelmin"] = 10;
			["prio"] = 26;
			["trg"] = "Player";
		};
		[27] = {
			["alias"] = "Reassemble <38";
			["condition"] = "";
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 2876;
			["ignoremoving"] = true;
			["levelmax"] = 37;
			["levelmin"] = 35;
			["maxRange"] = 0;
			["name"] = "Reassemble";
			["playerlevelmin"] = 10;
			["prio"] = 27;
			["trg"] = "Player";
		};
		[28] = {
			["alias"] = "Reassemble <35";
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 2876;
			["ignoremoving"] = true;
			["levelmax"] = 34;
			["levelmin"] = 12;
			["maxRange"] = 0;
			["name"] = "Reassemble";
			["playerlevelmin"] = 10;
			["prio"] = 28;
			["trg"] = "Player";
		};
	};
	["version"] = 3;
}
return obj1
