-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["classes"] = {
		[1] = true;
		[2] = false;
		[3] = false;
		[4] = false;
		[5] = false;
		[6] = false;
		[7] = false;
		[8] = false;
		[9] = false;
		[10] = false;
		[11] = false;
		[12] = false;
		[13] = false;
		[14] = false;
		[15] = false;
		[16] = false;
		[17] = false;
		[18] = false;
		[19] = true;
		[20] = false;
		[21] = false;
		[22] = false;
		[23] = false;
		[24] = false;
		[25] = false;
		[26] = false;
		[27] = false;
		[28] = false;
		[29] = false;
		[30] = false;
		[31] = false;
		[32] = false;
		[33] = false;
		[34] = false;
		[35] = false;
		[36] = false;
	};
	["filters"] = {
		[1] = "Stance Sheild/Sword";
		[2] = "AOE On/Off";
		[3] = "";
		[4] = "";
		[5] = "";
	};
	["skills"] = {
		[1] = {
			["condition"] = "";
			["filterfive"] = "On";
			["filterfour"] = "On";
			["gcdtime"] = 0.5;
			["id"] = 7533;
			["levelmin"] = 22;
			["maxRange"] = 25;
			["name"] = "Provoke";
			["prio"] = 1;
			["tbuff"] = "527";
			["tbuffowner"] = "Any";
			["tcontids"] = "2994";
		};
		[2] = {
			["filterfive"] = "Off";
			["filterfour"] = "On";
			["gcdtime"] = 0.5;
			["id"] = 7533;
			["levelmin"] = 22;
			["maxRange"] = 25;
			["name"] = "Provoke";
			["prio"] = 2;
			["tbuff"] = "526";
			["tbuffowner"] = "Any";
			["tcontids"] = "2994";
		};
		[3] = {
			["alias"] = "----- Stance -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 34;
			["maxRange"] = 0;
			["prio"] = 3;
			["used"] = false;
		};
		[4] = {
			["combat"] = "Any";
			["filterone"] = "Off";
			["gcd"] = "False";
			["gcdtime"] = 0.5;
			["id"] = 28;
			["ignoremoving"] = true;
			["levelmin"] = 30;
			["maxRange"] = 0;
			["name"] = "Shield Oath";
			["playerlevelmin"] = 30;
			["pnbuff"] = "79";
			["prio"] = 4;
			["trg"] = "Player";
		};
		[5] = {
			["combat"] = "Any";
			["filterone"] = "On";
			["gcd"] = "False";
			["gcdtime"] = 0.5;
			["id"] = 26;
			["levelmin"] = 35;
			["maxRange"] = 0;
			["name"] = "Sword Oath";
			["playerlevelmin"] = 35;
			["pnbuff"] = "381";
			["prio"] = 5;
			["trg"] = "Player";
		};
		[6] = {
			["alias"] = "----- Aggro -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 34;
			["maxRange"] = 0;
			["prio"] = 6;
			["used"] = false;
		};
		[7] = {
			["combat"] = "Any";
			["enmityaoe"] = true;
			["filterone"] = "Off";
			["filtertwo"] = "Off";
			["gcd"] = "False";
			["gcdtime"] = 0.5;
			["id"] = 14;
			["maxRange"] = 0;
			["name"] = "Flash";
			["onlyparty"] = true;
			["playerlevelmin"] = 6;
			["prio"] = 7;
			["tecount"] = 1;
			["terange"] = 5;
			["tncontids"] = "2832";
			["trg"] = "Player";
		};
		[8] = {
			["filterone"] = "Off";
			["gcdtime"] = 0.5;
			["id"] = 7533;
			["minRange"] = 6;
			["name"] = "Provoke";
			["onlyparty"] = true;
			["prio"] = 8;
			["tncontids"] = "2832";
			["trg"] = "Tankable Target";
		};
		[9] = {
			["alias"] = "----- Priority -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 34;
			["maxRange"] = 0;
			["prio"] = 9;
			["used"] = false;
		};
		[10] = {
			["combat"] = "Any";
			["gauge1gt"] = 50;
			["gcd"] = "False";
			["gcdtime"] = 0.5;
			["id"] = 3542;
			["levelmin"] = 52;
			["maxRange"] = 0;
			["name"] = "Sheltron";
			["playerlevelmin"] = 52;
			["prio"] = 10;
			["punderattack"] = true;
			["tcastonme"] = true;
			["tcasttime"] = "0.5";
			["trg"] = "Player";
		};
		[11] = {
			["gauge1eq"] = 100;
			["id"] = 3542;
			["levelmin"] = 52;
			["maxRange"] = 0;
			["name"] = "Sheltron";
			["playerlevelmin"] = 52;
			["prio"] = 11;
			["punderattack"] = true;
		};
		[12] = {
			["gcdtime"] = 0.5;
			["id"] = 25;
			["maxRange"] = 0;
			["name"] = "Shield Swipe";
			["playerlevelmin"] = 30;
			["prio"] = 12;
			["skready"] = "25";
		};
		[13] = {
			["gcdtime"] = 0.5;
			["id"] = 16;
			["levelmin"] = 18;
			["maxRange"] = 3;
			["name"] = "Shield Bash";
			["playerlevelmin"] = 18;
			["prio"] = 13;
			["tcasttime"] = "0.5";
		};
		[14] = {
			["gcdtime"] = 0.5;
			["id"] = 29;
			["levelmin"] = 45;
			["maxRange"] = 0;
			["name"] = "Spirits Within";
			["npcskill"] = "9,11,15";
			["playerlevelmin"] = 45;
			["prio"] = 14;
		};
		[15] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 30;
			["maxRange"] = 0;
			["name"] = "Hallowed Ground";
			["phpb"] = 35;
			["playerlevelmin"] = 50;
			["pnbuff"] = "74,83,77,72,82,71";
			["prio"] = 15;
			["pthpl"] = 80;
			["trg"] = "Player";
		};
		[16] = {
			["gcdtime"] = 0.5;
			["id"] = 3541;
			["levelmin"] = 58;
			["maxRange"] = 30;
			["name"] = "Clemency";
			["playerlevelmin"] = 58;
			["prio"] = 16;
			["pthpb"] = 50;
			["trg"] = "Party";
		};
		[17] = {
			["gcdtime"] = 0.5;
			["id"] = 3541;
			["levelmin"] = 58;
			["maxRange"] = 30;
			["name"] = "Clemency";
			["onlysolo"] = true;
			["phpb"] = 50;
			["playerlevelmin"] = 58;
			["pmppl"] = 99;
			["prio"] = 17;
		};
		[18] = {
			["gcdtime"] = 0.5;
			["id"] = 3540;
			["levelmin"] = 56;
			["maxRange"] = 0;
			["name"] = "Divine Veil";
			["onlyparty"] = true;
			["phpb"] = 80;
			["playerlevelmin"] = 56;
			["prio"] = 18;
			["pthpb"] = 80;
			["ptrg"] = "Enemy";
			["tacount"] = 2;
			["tahpl"] = 80;
			["tarange"] = 15;
			["trg"] = "Player";
		};
		[19] = {
			["alias"] = "----- Melee -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 34;
			["maxRange"] = 0;
			["prio"] = 19;
			["used"] = false;
		};
		[20] = {
			["id"] = 8754;
			["maxRange"] = 3;
			["name"] = "Requiescat";
			["pcskill"] = "3538,3539";
			["pnbuff"] = "76";
			["prio"] = 20;
		};
		[21] = {
			["gcdtime"] = 0.5;
			["id"] = 24;
			["maxRange"] = 15;
			["minRange"] = 6;
			["name"] = "Shield Lob";
			["playerlevelmin"] = 15;
			["prio"] = 21;
			["ptpl"] = 800;
			["ptrg"] = "Enemy";
		};
		[22] = {
			["filtertwo"] = "Off";
			["gcdtime"] = 0.5;
			["id"] = 23;
			["maxRange"] = 4;
			["name"] = "Circle of Scorn";
			["playerlevelmin"] = 50;
			["prio"] = 22;
			["ptrg"] = "Enemy";
			["tecount"] = 1;
			["terange"] = 4;
			["trg"] = "Player";
		};
		[23] = {
			["filtertwo"] = "Off";
			["id"] = 7381;
			["levelmin"] = 46;
			["maxRange"] = 0;
			["name"] = "Total Eclipse";
			["playerlevelmin"] = 46;
			["prio"] = 23;
			["tarange"] = 20;
			["tecenter"] = "Self";
			["tecount"] = 3;
			["terange"] = 5;
			["trg"] = "Player";
		};
		[24] = {
			["condition"] = "";
			["gcdtime"] = 0.5;
			["id"] = 21;
			["name"] = "Rage of Halone";
			["pcskill"] = "11";
			["playerlevelmin"] = 26;
			["prio"] = 24;
			["tnbuffowner"] = "Any";
		};
		[25] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 3538;
			["name"] = "Goring Blade";
			["pcskill"] = "15";
			["playerlevelmin"] = 54;
			["prio"] = 25;
			["tnbuff"] = "725";
			["tnbuffdura"] = 6;
		};
		[26] = {
			["gcdtime"] = 0.5;
			["id"] = 3539;
			["name"] = "Royal Authority";
			["pcskill"] = "15";
			["playerlevelmin"] = 60;
			["prio"] = 26;
			["tbuffowner"] = "Any";
		};
		[27] = {
			["gcdtime"] = 0.5;
			["id"] = 15;
			["name"] = "Riot Blade";
			["pcskill"] = "9";
			["playerlevelmin"] = 10;
			["prio"] = 27;
			["tankedonlyaoe"] = true;
		};
		[28] = {
			["alias"] = "Low Mp Riot";
			["gcdtime"] = 0.5;
			["id"] = 15;
			["levelmin"] = 12;
			["maxRange"] = 0;
			["name"] = "Riot Blade";
			["pcskill"] = "9";
			["playerlevelmin"] = 10;
			["pmppb"] = 50;
			["prio"] = 28;
			["tankedonlyaoe"] = true;
		};
		[29] = {
			["gcdtime"] = 0.5;
			["id"] = 11;
			["name"] = "Savage Blade";
			["pcskill"] = "9";
			["playerlevelmin"] = 4;
			["prio"] = 29;
		};
		[30] = {
			["gcdtime"] = 0.5;
			["id"] = 9;
			["maxRange"] = 0;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 30;
			["ptrg"] = "Enemy";
		};
		[31] = {
			["alias"] = "----- oGCD -----";
			["gcdtime"] = 0.5;
			["levelmin"] = 34;
			["maxRange"] = 0;
			["prio"] = 31;
			["used"] = false;
		};
		[32] = {
			["gcdtime"] = 0.5;
			["id"] = 19;
			["levelmin"] = 42;
			["maxRange"] = 0;
			["name"] = "Tempered Will";
			["pbuff"] = "13,14";
			["playerlevelmin"] = 42;
			["prio"] = 32;
		};
		[33] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 22;
			["maxRange"] = 0;
			["name"] = "Bulwark";
			["phpb"] = 60;
			["playerlevelmin"] = 46;
			["prio"] = 33;
			["ptrg"] = "Enemy";
			["trg"] = "Player";
		};
		[34] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 17;
			["ignoremoving"] = true;
			["maxRange"] = 0;
			["name"] = "Sentinel";
			["ncurrentaction"] = "10,32,17";
			["npskill"] = "10,32,17";
			["phpb"] = 50;
			["playerlevelmin"] = 38;
			["pnbuff"] = "71+83+74";
			["prio"] = 34;
			["ptrg"] = "Enemy";
			["trg"] = "Player";
		};
		[35] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 20;
			["maxRange"] = 0;
			["name"] = "Fight or Flight";
			["playerlevelmin"] = 2;
			["prio"] = 35;
			["ptrg"] = "Enemy";
			["trg"] = "Player";
		};
		[36] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 7531;
			["maxRange"] = 0;
			["name"] = "Rampart";
			["ncurrentaction"] = "10,32,17";
			["npskill"] = "10,32,17";
			["phpb"] = 70;
			["pnbuff"] = "71+83+74";
			["prio"] = 36;
			["ptrg"] = "Enemy";
			["trg"] = "Player";
		};
		[37] = {
			["dobuff"] = true;
			["gcdtime"] = 0.5;
			["id"] = 7532;
			["maxRange"] = 0;
			["name"] = "Convalescence";
			["onlyparty"] = true;
			["phpb"] = 60;
			["prio"] = 37;
			["ptrg"] = "Enemy";
			["trg"] = "Player";
		};
		[38] = {
			["gcdtime"] = 0.5;
			["id"] = 7534;
			["maxRange"] = 3;
			["name"] = "Awareness";
			["phpb"] = 98;
			["prio"] = 38;
			["ptrg"] = "Enemy";
		};
	};
	["update"] = 20190307;
	["version"] = 3;
}
return obj1
