-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["classes"] = {
		[1] = false;
		[2] = false;
		[3] = false;
		[4] = false;
		[5] = false;
		[6] = false;
		[7] = false;
		[8] = false;
		[9] = false;
		[10] = false;
		[11] = false;
		[12] = false;
		[13] = false;
		[14] = false;
		[15] = false;
		[16] = false;
		[17] = false;
		[18] = false;
		[19] = false;
		[20] = false;
		[21] = false;
		[22] = false;
		[23] = false;
		[24] = false;
		[25] = false;
		[26] = false;
		[27] = false;
		[28] = false;
		[29] = false;
		[30] = false;
		[31] = false;
		[32] = false;
		[33] = false;
		[34] = true;
		[35] = false;
	};
	["filters"] = {
		[1] = "";
		[2] = "AOE Off";
		[3] = "";
		[4] = "Hagakure Off";
		[5] = "";
	};
	["skills"] = {
		[1] = {
			["alias"] = "-- Priorities --";
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 1;
			["used"] = false;
		};
		[2] = {
			["id"] = 7863;
			["levelmin"] = 16;
			["maxRange"] = 3;
			["name"] = "Leg Sweep";
			["pnbuff"] = "1231+1229+1233";
			["prio"] = 2;
			["tcasttime"] = "0.1";
		};
		[3] = {
			["id"] = 7544;
			["levelmin"] = 24;
			["maxRange"] = 0;
			["name"] = "Invigorate";
			["playerlevelmin"] = 24;
			["pnbuff"] = "1231+1233";
			["prio"] = 3;
			["ptpb"] = 50;
		};
		[4] = {
			["id"] = 7498;
			["levelmin"] = 6;
			["maxRange"] = 0;
			["name"] = "Third Eye";
			["phpb"] = 75;
			["playerlevelmin"] = 6;
			["pnbuff"] = "1231+1233";
			["prio"] = 4;
			["punderattack"] = true;
			["punderattackmelee"] = true;
			["trg"] = "Player";
			["trgself"] = true;
		};
		[5] = {
			["gcd"] = "False";
			["id"] = 7502;
			["levelmin"] = 58;
			["maxRange"] = 0;
			["name"] = "Merciful Eyes";
			["prio"] = 5;
			["skready"] = "7502";
			["trg"] = "Player";
			["trgself"] = true;
		};
		[6] = {
			["id"] = 7549;
			["levelmin"] = 40;
			["maxRange"] = 10;
			["name"] = "Feint";
			["pnbuff"] = "1231+1229+1233";
			["prio"] = 6;
		};
		[7] = {
			["combat"] = "Any";
			["gcd"] = "False";
			["id"] = 7541;
			["levelmin"] = 8;
			["maxRange"] = 0;
			["name"] = "Second Wind";
			["phpb"] = 50;
			["playerlevelmin"] = 8;
			["pnbuff"] = "1231+1233";
			["prio"] = 7;
			["trg"] = "Player";
			["trgself"] = true;
		};
		[8] = {
			["gcd"] = "False";
			["id"] = 7542;
			["levelmin"] = 32;
			["maxRange"] = 0;
			["name"] = "Bloodbath";
			["phpb"] = 45;
			["playerlevelmin"] = 32;
			["prio"] = 8;
			["trg"] = "Player";
			["trgself"] = true;
		};
		[9] = {
			["id"] = 7545;
			["levelmin"] = 20;
			["maxRange"] = 0;
			["name"] = "Diversion";
			["phpb"] = 80;
			["phpl"] = 1;
			["playerlevelmin"] = 20;
			["pnbuff"] = "1231+1233";
			["prio"] = 9;
			["punderattack"] = true;
			["punderattackmelee"] = true;
			["trg"] = "Player";
		};
		[10] = {
			["filterfour"] = "Off";
			["id"] = 7495;
			["levelmin"] = 68;
			["maxRange"] = 0;
			["name"] = "Hagakure";
			["pbuff"] = "1299";
			["pbuffdura"] = 2;
			["pnbuff"] = "1233+1229";
			["prio"] = 10;
			["sknready"] = "7487";
			["thpl"] = 35;
			["tnbuff"] = "1228";
			["trg"] = "Player";
			["trgself"] = true;
		};
		[11] = {
			["alias"] = "-- AOE --";
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 11;
			["used"] = false;
		};
		[12] = {
			["filtertwo"] = "Off";
			["frontalconeaoe"] = true;
			["gauge2or"] = "3,6";
			["id"] = 7488;
			["levelmin"] = 30;
			["maxRange"] = 0;
			["name"] = "Tenka Goken";
			["pgskill"] = "7485";
			["playerlevelmin"] = 40;
			["pnbuff"] = "1233";
			["prio"] = 12;
		};
		[13] = {
			["filtertwo"] = "Off";
			["id"] = 7485;
			["levelmin"] = 45;
			["maxRange"] = 0;
			["name"] = "Oka";
			["pcskill"] = "7483";
			["playerlevelmin"] = 45;
			["pnbuff"] = "1229+1233";
			["prio"] = 13;
			["ptpb"] = 1000;
			["ptpl"] = 160;
			["skready"] = "7489";
			["tarange"] = 5;
			["tecount"] = 2;
			["terange"] = 5;
			["trg"] = "Player";
		};
		[14] = {
			["filtertwo"] = "Off";
			["id"] = 7484;
			["levelmin"] = 35;
			["maxRange"] = 0;
			["name"] = "Mangetsu";
			["pcskill"] = "7483";
			["playerlevelmin"] = 35;
			["pnbuff"] = "1229+1233";
			["prio"] = 14;
			["ptpb"] = 1000;
			["ptpl"] = 160;
			["sknready"] = "7489";
			["tarange"] = 5;
			["tecount"] = 2;
			["terange"] = 5;
			["trg"] = "Player";
		};
		[15] = {
			["filtertwo"] = "Off";
			["frontalconeaoe"] = true;
			["id"] = 7483;
			["levelmin"] = 26;
			["maxRange"] = 6;
			["name"] = "Fuga";
			["playerlevelmin"] = 26;
			["pnbuff"] = "1229+1233";
			["prio"] = 15;
			["ptpb"] = 1000;
			["ptpl"] = 160;
			["tarange"] = 6;
			["tecount"] = 2;
			["terange"] = 6;
		};
		[16] = {
			["alias"] = "-- Single Target --";
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 16;
			["used"] = false;
		};
		[17] = {
			["alias"] = "MS Kasha";
			["gauge2or"] = "0,1,2,3";
			["id"] = 7482;
			["levelmin"] = 40;
			["maxRange"] = 3;
			["name"] = "Kasha";
			["pbuff"] = "1233";
			["playerlevelmin"] = 40;
			["prio"] = 17;
		};
		[18] = {
			["alias"] = "MS Gekko";
			["gauge2or"] = "0,1,4,5";
			["id"] = 7481;
			["levelmin"] = 30;
			["maxRange"] = 3;
			["name"] = "Gekko";
			["pbuff"] = "1233";
			["playerlevelmin"] = 30;
			["prio"] = 18;
		};
		[19] = {
			["alias"] = "MS Yuki";
			["gauge2or"] = "0,2,4,6";
			["id"] = 7480;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Yukikaze";
			["pbuff"] = "1233";
			["playerlevelmin"] = 50;
			["prio"] = 19;
		};
		[20] = {
			["gauge2gt"] = 7;
			["id"] = 7487;
			["levelmin"] = 30;
			["maxRange"] = 0;
			["name"] = "Midare Setsugekka";
			["playerlevelmin"] = 50;
			["prio"] = 20;
		};
		[21] = {
			["gcd"] = "False";
			["id"] = 7494;
			["levelmin"] = 52;
			["maxRange"] = 3;
			["name"] = "Hissatsu: Kaiten";
			["pnbuff"] = "1231+1229+1233";
			["prio"] = 21;
			["ptrg"] = "Enemy";
			["skready"] = "7500";
			["thpb"] = 20;
			["trg"] = "Player";
			["used"] = false;
		};
		[22] = {
			["id"] = 7500;
			["levelmin"] = 10;
			["maxRange"] = 3;
			["name"] = "Ageha";
			["playerlevelmin"] = 10;
			["pnbuff"] = "1231+1233";
			["prio"] = 22;
			["thpb"] = 20;
		};
		[23] = {
			["gcd"] = "False";
			["id"] = 7494;
			["levelmin"] = 52;
			["maxRange"] = 3;
			["name"] = "Hissatsu: Kaiten";
			["pnbuff"] = "1231+1229+1233";
			["prio"] = 23;
			["sknready"] = "7487";
			["skready"] = "7489";
			["thpb"] = 100;
			["thpl"] = 10;
			["tnbuff"] = "1228";
			["tnbuffdura"] = 10;
			["trg"] = "Player";
			["trgself"] = true;
		};
		[24] = {
			["gauge2or"] = "1,2,4";
			["id"] = 7489;
			["maxRange"] = 8;
			["name"] = "Higanbana";
			["pbuff"] = "1298";
			["playerlevelmin"] = 30;
			["pnbuff"] = "1231+1233";
			["prio"] = 24;
			["sknready"] = "7487";
			["skready"] = "7489";
			["tnbuff"] = "1228";
			["tnbuffdura"] = 10;
		};
		[25] = {
			["gcd"] = "False";
			["id"] = 7494;
			["levelmin"] = 52;
			["maxRange"] = 3;
			["name"] = "Hissatsu: Kaiten";
			["pnbuff"] = "1231+1229";
			["prio"] = 25;
			["skready"] = "7487";
			["trg"] = "Player";
			["trgself"] = true;
		};
		[26] = {
			["dobuff"] = true;
			["gauge2or"] = "0";
			["id"] = 7499;
			["levelmin"] = 50;
			["maxRange"] = 0;
			["name"] = "Meikyo Shisui";
			["playerlevelmin"] = 50;
			["pnbuff"] = "1231";
			["prio"] = 26;
			["ptrg"] = "Enemy";
			["sknready"] = "7867,7487,7488,7489";
			["skready"] = "7499";
			["tbuff"] = "1228";
			["thpl"] = 25;
			["trg"] = "Player";
			["trgself"] = true;
		};
		[27] = {
			["gauge1gt"] = 25;
			["gcd"] = "False";
			["id"] = 7490;
			["levelmin"] = 62;
			["maxRange"] = 3;
			["name"] = "Hissatsu: Shinten";
			["prio"] = 27;
			["secspassed"] = 15;
			["sknready"] = "7487";
		};
		[28] = {
			["alias"] = "-- Teir 3 --";
			["id"] = 9;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 28;
			["used"] = false;
		};
		[29] = {
			["id"] = 7482;
			["maxRange"] = 3;
			["name"] = "Kasha";
			["pcskill"] = "7479";
			["prio"] = 29;
		};
		[30] = {
			["id"] = 7481;
			["maxRange"] = 3;
			["name"] = "Gekko";
			["pcskill"] = "7478";
			["prio"] = 30;
		};
		[31] = {
			["alias"] = "-- Teir 2 Sen --";
			["id"] = 9;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 31;
			["used"] = false;
		};
		[32] = {
			["gauge2or"] = "0,1,2,3";
			["id"] = 7479;
			["levelmin"] = 40;
			["maxRange"] = 3;
			["name"] = "Shifu";
			["pcskill"] = "7477";
			["prio"] = 32;
		};
		[33] = {
			["gauge2or"] = "0,1,4,5";
			["id"] = 7478;
			["levelmin"] = 30;
			["maxRange"] = 3;
			["name"] = "Jinpu";
			["pcskill"] = "7477";
			["prio"] = 33;
		};
		[34] = {
			["gauge2or"] = "0,2,4,6";
			["id"] = 7480;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Yukikaze";
			["pcskill"] = "7477";
			["prio"] = 34;
		};
		[35] = {
			["gauge2or"] = "0,2,4,6";
			["id"] = 7477;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Hakaze";
			["prio"] = 35;
		};
		[36] = {
			["alias"] = "Teir 2 Buff Timer --";
			["id"] = 9;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 36;
		};
		[37] = {
			["id"] = 7479;
			["levelmin"] = 18;
			["maxRange"] = 3;
			["name"] = "Shifu";
			["pcskill"] = "7477";
			["pnbuff"] = "1299";
			["pnbuffdura"] = 10;
			["prio"] = 37;
		};
		[38] = {
			["id"] = 7478;
			["levelmin"] = 4;
			["maxRange"] = 3;
			["name"] = "Jinpu";
			["pcskill"] = "7477";
			["pnbuff"] = "1298";
			["pnbuffdura"] = 10;
			["prio"] = 38;
		};
		[39] = {
			["id"] = 7480;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Yukikaze";
			["pcskill"] = "7477";
			["prio"] = 39;
			["tnbuff"] = "819";
			["tnbuffdura"] = 10;
			["tnbuffowner"] = "Any";
		};
		[40] = {
			["id"] = 7477;
			["levelmin"] = 50;
			["maxRange"] = 3;
			["name"] = "Hakaze";
			["prio"] = 40;
			["tnbuff"] = "819";
			["tnbuffdura"] = 10;
			["tnbuffowner"] = "Any";
		};
		[41] = {
			["alias"] = "-- Teir 1 --";
			["id"] = 9;
			["levelmin"] = 1;
			["maxRange"] = 3;
			["name"] = "Fast Blade";
			["playerlevelmin"] = 1;
			["prio"] = 41;
			["used"] = false;
		};
		[42] = {
			["id"] = 7479;
			["levelmin"] = 18;
			["maxRange"] = 3;
			["name"] = "Shifu";
			["pcskill"] = "7477";
			["playerlevelmin"] = 18;
			["prio"] = 42;
		};
		[43] = {
			["id"] = 7478;
			["levelmin"] = 4;
			["maxRange"] = 3;
			["name"] = "Jinpu";
			["pcskill"] = "7477";
			["playerlevelmin"] = 4;
			["prio"] = 43;
		};
		[44] = {
			["combat"] = "Any";
			["id"] = 7477;
			["maxRange"] = 3;
			["name"] = "Hakaze";
			["prio"] = 44;
		};
	};
	["version"] = 3;
}
return obj1
