ffxiv_strings =
{	
	-- bk: EN
    ["en"] =
    {
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "CombatMovement",
        enableRepair                    = "AutoRepair",
        ignoreMarkerLevels              = "IgnoreMarkerLevels",
        ["Bot Status"]                  = "BotStatus",
        settings                        = "Settings",
		status							= "Status",
        vendorSettings                  = "VendorSettings",
        gatherSettings                  = "GatherSettings",
        skipcutscene					= "Skip Cutscenes",
		depositItems					= "Deposit Items",
		checkChat						= "Chat Alert",
		randomfarmspot 					= "Use Random Farmspots",
		disabledrawing 					= "Disable Rendering",
		killaggrononfateenemies 		= "Kill attacking None-Fate Enemies",
		avoidAOE						 = "Avoid AOE",
		smoothFacing					 = "Smooth Facing",
		smoothFacingRatio				 = "Smooth Facing Ratio",
        -- mesher.lua
        meshManager                     = "MeshManager", 	
		activated                       = "Activated",
		noMeshLoad						= "No Mesh Load",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        ["General"]                 	= "General",
		["Auto-Equip"]					= "Auto-Equip",
		getWaypoint						= "GetMeshWP",
		useInSwitcher					= "UseInSwitcher",
		enableSwitcher					= "EnableSwitcher",
		minSwitchTime			        = "MinSwitchTime",
		maxSwitchTime					= "MaxSwitchTime",
		switchTimer						= "TimeUntilSwitch",
		switcherSettings				= "SwitcherSettings",
		showMesh						= "Show Triangles ",
		showrealMesh					= "Show NavMesh",
		newMeshName						= "New Meshfile Name",
		newMesh							= "Clear Navmesh",
		saveMesh						= "Save NavMesh",
		buildNAVMesh					= "Build NavMesh",
		editor							= "Edit Mesh",
		recoder							= "Record Mesh",
		connections						= "Connections",
        enablePSwitch					= "EnableParanoiaSwitch",
        pSwitchCount                    = "ParanoiaPlayerCount",		
        maMarkerID                      = "ID",
        maMarkerName                    = "Name",
		
        -- skillmanager.lua
		skillbook                 	 	= "SkillBook",
		skillManager                    = "SkillManager",
		skillEditor_craft              	= "SkillEditor_Crafting",
        skillEditor_gather            	= "SkillEditor_Gathering",
		saveProfile                 	= "Save Profile",
		newProfileName                  = "New Profile",
		skillProfile					= "Skill Profile",
        newProfile                      = "Create New Profile",
		clearProfile					= "Clear Profile",
		skillbookrefresh                = "Refresh Skills",
		targetType                      = "Target",
		stepmin							= "Step >=",
		stepmax							= "Step <",
		durabmin						= "Durability >=",
		durabmax						= "Durability <",
		progrmin						= "Progress >=",
		progrmax						= "Progress <",
		qualitymin						= "Quality >=",
		qualitymax						= "Quality <",
		condition						= "Condition =",
		cpmin							= "CP >=",
		cpmax							= "CP <",
        gpmin							= "GP >=",
		gpmax							= "GP <",
		iqstack							= "InnerQuiet Stack >=",		
		notused							= "NotUsed",
		excellent						= "Excellent",
		good							= "Good",
		normal							= "Normal",
		poor							= "Poor",
		centered						= "Centered",
		sturdy							= "Sturdy",
		pliant							= "Pliant",
		primed							= "Primed",
		malleable						= "Malleable",
		
        nodeHas						    = "Has Item: ",
		gatherAttemptsMin				= "Attempts Remaining >",
		gatherAttemptsMax				= "Attempts Remaining <=",
        profile                         = "Profile",
		sMmode							= "Attack Mode",
		sMtargetmode					= "Target Mode",
		refreshProfiles                 = "Refresh Profile List",			
        deleteProfile                   = "Delete Current Profile",
        autoetectSkills                 = "Autodetect Skills",
		refreshSkillList                = "Clear & Refresh SkillList",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
		appliesBuff                     = "Applies (De-)Buff",
        priority                        = "Priority",
        los                  		    = "Needs LineOfSight",
		instacast            		    = "Instant Skill",
		channeled            		    = "Channel Skill",		
		cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "Is GroundTargeted",        
        useOutOfCombat                  = "Use out of Combat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player MP >",
        playerPowerLT                   = "Player MP <",
        playerHas                       = "Player has Buff: like 13,4152,521",
        orPlayerHas                     = "or Player has ",
        playerHasNot                    = "Player has NOT Buff: like 13,4152,521",
		orPlayerCond					= "Player has #Conditions >",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has Buff : like 13,4152,521",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT Buff : like 13,4152,521",
        orTargetHasNot                  = "or Target has NOT ",
		prevSkillID						= "Previous Skill ID",
		Fightstyle						= "Fightstyle",
		
		
		--new SKM stuff
		alias							= "Alias",
		cdIsReady						= "CD Is Ready",
		cdNotReady						= "CD Not Ready",
		cdTimeLT						= "CD Time <=",
		cdTimeGT						= "CD Time >=",
		nextSkillPrio					= "Next Skill Prio",
		skmTYPE							= "Action Type",
		skmSTYPE					 	= "Skill Type",
		skmCombat						= "Combat Status",
		skmCHARGE						= "Charge Skill",
		skmLevelMin						= "Level >=",
		skmLevelMax						= "Level <=",
		checkSkill						= "Skill ID",
		isReady 						= "Is Ready",
		isNotReady						= "Is Not Ready",
		cooldownRemainingLTE			= "Cooldown Remaining <=",
		cooldownRemainingGTE			= "Cooldown Remaining >=",
		skmNSkillID						= "Next Skill ID",
		skmCBreak						= "Combo Breaker",
		skmTRG							= "Skill Target",
		skmTRGTYPE						= "Target Role",
		skmNPC							= "Include NPC",
		skmPTRG							= "Player Target",
		skmPGTRG						= "Ground Target",
		skmPPos							= "Position",
		skmTHPCL						= "Target HP >",
		skmTHPCB						= "Target HP <",
		skmTCONTIDS						= "Content ID(s)",
		skmTNCONTIDS					= "Not Content ID(s)",
		skmTCASTID						= "Cast ID(s)",
		skmTCASTTM						= "Cast @ Me",
		skmTCASTTIME					= "Cast Time >",
		skmPTPL							= "Player TP >",
		skmPTPB							= "Player TP <",
		skmPMPPL                		= "Player MP% >",
        skmPMPPB                  		= "Player MP% <",
		skmPAGL							= "Player Aggro % >",
        skmPAGB							= "Player Aggro % <",
		skmMPLock						= "Causes MP Lockout",
		skmMPLocked						= "Lockout Affected",
		skmMPLockPer					= "MP Lockout %",
		skmPTCount						= "Member Count >=",
		skmPTHPL						= "Party HP% >",
		skmPTHPB						= "Party HP% <",
		skmPTMPL						= "Party MP% >",
		skmPTMPB						= "Party MP% <",
		skmPTTPL						= "Party TP >",
		skmPTTPB						= "Party TP <",
		skmHPRIOHP						= "Priority HP % <",
		skmHPRIO1						= "Heal Priority 1",
		skmHPRIO2						= "Heal Priority 2",
		skmHPRIO3						= "Heal Priority 3",
		skmHPRIO4						= "Heal Priority 4",
		skmTECount						= "Enemies >=",
		skmTECount2						= "Enemies <=",
		skmTERange						= "Enemy Range",
		skmTELevel						= "Level Difference",
		skmTACount						= "Allies >=",
		skmTARange						= "Ally Range",
		skmTBuffOwner					= "Buff Owner",
		skmHasBuffs						= "Has Buffs (1+2,3)",
		skmMissBuffs					= "Missing Buffs (1+2,3)",
		skmOrBuffDura					= "Or Buff Dura <=",
		skmAndBuffDura					= "And Buff Dura >",
		skmUnspoiled					= "Unspoiled Node",		
		up								= "UP",
		down							= "DOWN",
		delete							= "DELETE",
		copy							= "COPY",
		paste							= "PASTE",
		--sections						
		skillDetails					= "Skill Details",
		skillChecks						= "Other Skill Checks",
		basicDetails					= "Basic Details",
		playerHPMPTP					= "Player HP/MP/TP",
		party							= "Party",
		target							= "Target",
		casting							= "Casting",
		healPriority					= "Heal Priority",
		aoe								= "AOE",
		playerBuffs						= "Player Buffs",
		targetBuffs						= "Target Buffs",
		
        --ffxiv stuff specific stuff
        botMode                       	= "Bot Mode",
        addGrindSpot                    = "Add Grind Marker",
        addFishingSpot                  = "Add Fishing Marker",
        addMiningSpot                   = "Add Mining Marker",
        addBotanySpot                   = "Add Botany Marker",
        addNavSpot                      = "Add Nav Marker",		
        deleteSpot                      = "Delete Nearest Marker",
        markers                         = "Markers",
        markerLevel						= "Marker Level",
        markerMinLevel				    = "Marker Min Level",
        markerMaxLevel				    = "Marker Max Level",
        selectedMarker                  = "Selected Marker",
		noMarker						= "No Marker",
        mining                          = "Mining",
        fishing                         = "Fishing",
        botany                          = "Botany",
		gatherTime 						= "Marker Timer (s)",
		recmesh							= "Record Mesh",
		recAreaType						= "Record Type",
		recAreaSize						= "Record Size",
		changeMesh						= "Change Mesh",
		changeAreaType					= "Change Type",
		changeAreaSize					= "Change Size",		
		biDirOffMesh					= "Bidirectional Offmeshconnection",
		addOffMeshSpot					= "Add OffMeshConnection",
		delOffMeshSpot					= "Del OffMeshConnection",
		typeOffMeshSpot					= "Type OffMeshConnection",
		showPath						= "Show Path",
        selectItem1                     = "Item Priority 1",
        selectItem2                     = "Item Priority 2",
		selectItem3                     = "Item Priority 3",
        selectBait                      = "Select Bait",
        baitName                        = "Bait Name",
        markerName                      = "Marker Name",
        markerPos                       = "Marker Position",
        selectClosestMarker             = "Select Closest Marker",
        moveToMarker                    = "Move To Marker",
        gatherManager                   = "GatherManager",
        selectMarker                    = "Select Marker",
        logCNE                          = "Log CNE Results",
        useMount                        = "Use Mount",
        useSprint                       = "Use Sprint",
		gatherGardening					= "Gather Gardening",
		gatherChocoFood					= "Gather Choco Food",
		nodeType						= "Node Type",
		throttle						= "Throttle",
		--**********************************************
		repair							= "Repair",
		questHelpers					= "Quest Helpers",
		mount							= "Mount",
		companion						= "Companion",
		stance							= "Stance",
		stFollow						= "Follow",
		stFree							= "Free Stance",
		stDefender						= "Defender Stance",
		stAttacker						= "Attacker Stance",
		stHealer						= "Healer Stance",
		--**********************************************
        mountDist                       = "Mount Distance: ",
        sprintDist                      = "Sprint Distance: ",
		randomPaths						= "Randomize Paths",
        botEnabled                      = "Bot Enabled",
        grindMode                       = "Grind",
		huntMode						= "Hunt",
		huntlogMode						= "Hunting Log",
        fishMode                        = "Fish",
        gatherMode                      = "Gather",
        assistMode                      = "Assist",
        partyMode                       = "Party-Grind",
		craftMode                       = "Crafting",
        useStealth                      = "Use Stealth",
        randomizeMarkers                = "Randomize Markers",
        teleport                        = "Teleport",
        permaSprint                     = "PermaSprint",
		avoidHP							= "Avoid HP% ",
        restHP                          = "Rest HP%: ",
        restMP                          = "Rest MP%: ",
        fleeHP                          = "Flee HP%: ",
        fleeMP                          = "Flee MP%: ",
        doFates                         = "Do Fates",
        fatesOnly                       = "Fates Only",
        setEvacPoint                    = "SetEvacPoint",
        restInFates                     = "Rest In Fates",
        maxFateLevel                    = "MaxFateLvl: +",
        minFateLevel                    = "MinFateLvl: -",
        waitForComplete                 = "WaitForComplete%: ",
        blacklistTimer                  = "BlacklistTimer (s)",
        fateIndex                       = "FateIndex",
        fateName                        = "FateName",
        blacklistAdd                    = "BlacklistAdd",
        blacklistRem                    = "BlacklistRem",
        enableRadar                     = "Enable Radar",
        enable2DRadar                   = "Enable 2D Radar",
        enable3DRadar                   = "Enable 3D Radar",
        fullscreenRadar                 = "Fullscreen (2D)",
        showNodes                       = "Show Nodes",
        showPlayers                     = "Show Players",
        showBattleNPCs                  = "Show Battle NPCs",
        showEventNPCs                   = "Show Event NPCs",
        showEventObjects                = "Show Event Objects",
        showAetherytes                  = "Show Aetherytes",
        xPos                            = "X Position",
        yPos                            = "Y Position",
        assist                          = "Targeting Assist",
        assistPriority            	    = "Priority",
		
		-- new stuff (since last translation)
		useMooch						= "Use Mooch",
		markerManager					= "MarkerManager",
		prevSkillIDNot				 	= "Previous Skill ID NOT",
		secsSinceLastCast				= "Secs Since Last Cast",
        combatRangePercent              = "Combat Range %: ",
        blacklistManager                = "BlacklistManager",
		createMarker				 	= "Create Marker",
		editMarkers						= "Edit Markers",
		editMarkerList					= "Setup List",
		addMarker					 	= "Add To List",
		editMarker						= "Edit Marker",
		newMarker						= "New Marker",
		setupList						= "Setup List",
        blacklistName                   = "Blacklist Name",
        blacklistEntry                  = "Blacklist Entry",
        entryTime                       = "Entry Time",
        deleteEntry                     = "Delete Entry",
        qualityminper					= "Quality % >=",
		qualitymaxper					= "Quality % <",
        blacklistTarget                 = "Blacklist Target",
        addEntry                        = "Add Entry",
        blacklistFate                   = "Blacklist Fate",
        notAttackable                   = "Invalid Target",
        targetName                      = "Target Name",
        monsters                        = "Monsters",
        fates                           = "Fates",
		--*************************************************
		toggleOnOff						= "Toggle On/Off",
		multiManager					= "Multibot Manager",
		multiChannel 					= "Channel",
		multiServer						= "Server IP",
		multiPort			 			= "Port #",
		multiPass    					= "Password",
		serverInfo				    	= "Server Information",
		--*************************************************
		huntMonsters					= "Hunted Monsters",
		hunt							= "Hunt",
		doAtma							= "Do Atma",
		prioritizeClaims				= "Prioritize Claims",
		claimRange						= "Claim Range",
		attackClaimed					= "Attack Claimed",
		alwaysKillAggro					= "Always Kill Aggro",
		fateTeleportPercent				= "Teleport %",
		--***************************************************
        startCombat                     = "Start Combat",
		onlySolo						= "Only solo",
		onlyParty						= "Only in party",
		alliesNearHPLT					= "Allies HP% <",
        --new
        pvpMode                         = "PVP",
        pve                             = "PVE",
        both                            = "Both",
        pvpTargetType                   = "PVP Target Type",
        healer                          = "Healer",
        dps                             = "DPS",
        tank                            = "Tank",
        any                             = "Any",
		none						 	= "None",
		
		meleeDPS						= "Melee DPS",
		caster							= "Caster",
		ranged							= "Ranged",
		nearDead						= "Near Dead",
		sleeper							= "Sleeper",
		unattendedHealer				= "Unattended Healer",
		
        prioritizeRanged                = "Prioritize Ranged",
        combatType                      = "Combat Type",
        nearest                         = "Nearest",
        lowestHealth                    = "Lowest Health",
        highestHealth                   = "Highest Health",
		tankAssist						= "Tank Assist",
        pvpTargetOne                    = "Priority 1",
        pvpTargetTwo                    = "Priority 2",
		pvpTargetThree					= "Priority 3",
		pvpTargetFour					= "Priority 4",
		pvpTargetFive					= "Priority 5",
		pvpAvoid						= "Avoidance",
		pvpSpeedMatchPartner			= "Speed Match Partner",
		pvpArena						= "PVP Arena",
		
		gatherMaps						= "Gather Maps",
        markerFields                    = "Marker Fields",
		confirmDuty						= "Auto-Confirm Duty",
		antiAFKMove						= "Anti-AFK Move",
		pvpFlee							= "Ranged Flee",
        skipCutscene                    = "Skip Cutscenes",
        skipDialogue                    = "Skip Dialogues",
        doUnstuck                       = "Enable Unstuck",
        delayLeave                      = "Delay Leave",
        defaultProfile                  = "Default Profile",
		enterDutyTimer 					= "Enter Timer: ",
		leaveDutyTimer 					= "Leave Timer: ",
		dutyMode						= "Duty",
		dutyLeader						= "Duty Leader: ",
        clickToTeleport                 = "Click To Teleport",
        clickToTravel                   = "Click To Travel",
		questRunProfile					= "RunQuests",
		questManager					= "QuestManager",		
		quests							= "Quests",
		questEditor						= "Quest Editor",
		questDone						= "Quest Done",
		questInfo						= "Quest Information",
		questSteps						= "Steps",
		questDo							= "Do Quest Now",
		questAddQuest					= "Add New Quest",
		questAddStep					= "Add New Step",
		questAddTurnover				= "Add New Turn-In",
		questAddPreReq					= "Add New Pre-Req",
		questID							= "Quest ID",
		questPullID						= "Pull Quest ID",
		questPullValues					= "Pull Current Values",
		questJob						= "Quest Job",
		questLevel						= "Quest Level",
		questSave						= "Save Quest",
		questDelete						= "Delete Quest",
		questUp 						= "Higher Priority",
		questDown						= "Lower Priority",
		questStepEditor					= "Step Editor",
		questStep						= "Step",
		questStepInfo					= "Step Information",
		questStepDetails				= "Script Details",
		questAddItem					= "Add Item",
		questClearItems					= "Clear Items",
		questItemEditor					= "Item Editor",
		newItem							= "New Item",
		stepItemAmount					= "Amount",
		items							= "Items",
		convoIndex						= "Conversation #",
		dutyEncounters					= "Encounters",
		dutyEncounterEditor				= "Edit Duty Encounter",
		
		questStepScript					= "Task-Script",
		questStepDelete					= "Delete Step",
		questStepSave					= "Save Step",
		questTurnoverEditor				= "Turn-In Editor",
		questPreReqEditor				= "Prerequisite Editor",
		questName						= "Name",		
		questMinLevel					= "Min Level",
		questMaxLevel					= "Max Level",
		questPreQuest					= "Needs Previous Quest",
		questMap						= "Map",
		questRepeat						= "Repeatable",
		questStepDone					= "Step Done",
		questReset						= "Reset Questprogress",
		markerList						= "Marker List",
		markerTeam						= "Marker Team",
		singleMarker					= "Single Marker",
		randomMarker					= "Random Marker",
		questMode						= "Quest",
		removeMarker					= "Remove Marker",
		deleteMarker					= "Delete Marker",
		PartyGrind         				= "Party Grind",
		PartyLeader         			= "Leader",
		GetPartyLeader      			= "Target->Leader",
		UseGamePartyLeader  			= "Use Party Leader",
		TargetIsCasting           		= "Target Casting",
		TargetCastingOnMe           	= "Casting On Me",
		TargetCastingTime           	= "Casting Time >",
        botanyMarker                    = "Botany Marker",
        miningMarker                    = "Mining Marker",
        grindMarker                     = "Grind Marker",
		huntMarker						= "Hunt Marker",
		pvpMarker						= "PVP Marker",
		unspoiledMarker					= "Unspoiled Marker",
        contentIDEquals                 = "ContentID=",
        NOTcontentIDEquals              = "NOT ContentID=",
		fishingMarker					= "Fishing Marker",
		time							= "Time (s)",
		name							= "Name",
		minLevel						= "Min Level",
		maxLevel						= "Max Level",
		markerTime						= "Marker Time (s)",
		useAetherytes					= "Use Aetherytes",
		resetDutyTimer 					= "Reset Timer: ",
		createProfile					= "Create Profile",
		existingProfile					= "Existing Profile:",
		profileType						= "Profile Type:",
		customTask						= "Custom Task",
		addEncounter					= "Add Encounter",
		details							= "Details",
		newEncounter					= "New Encounter",
		newQuest						= "New Quest",
		editQuestStep					= "Edit Quest Step",
		newQuestStep					= "New Step",
		newQuestTurnover				= "New Turn-In",
		newQuestPreReq					= "New Pre-Req",
		questEditSteps					= "Edit Steps",
		questEditPreReqs				= "Edit Pre-Reqs",
		questEditTurnovers				= "Edit Turn-Ins",
		stepCurrent						= "Current Step",
		stepTask						= "Step Task",
		stepItemSelector				= "Select Item",
		stepItemID						= "Item ID",
		stepQuestID						= "Quest ID",
		stepTaskCustom					= "Step Task Custom",
		stepMap							= "Map ID",
		stepMesh						= "Mesh Name",
		stepTarget						= "Step Target",
		stepAction						= "Action ID",
		stepCommandString				= "Command String",
		stepKillCount					= "Kill Count",
		stepDelay						= "Delay",
		stepReward						= "Reward Slot",
		stepClear						= "Clear All Steps",
		prereqJob						= "PreReq Job",
		prereqStep						= "PreReq Step",
		prereqID						= "PreReq ID",
		prereqClear						= "Clear All PreReqs",
		turnoverStep					= "Step #:",
		turnoverID						= "Turn-In ID",
		turnoverSlot					= "Item Slot",
		turnoverClear					= "Clear All Turn-Ins",
		profileManager					= "Profile Manager",
		advancedSettings				= "Advanced Settings",
		hacks							= "Hacks",
		newLocation						= "New Location",
		startLocation					= "Start Location",
		addLocation						= "Add Location",
		saveLocation					= "Save Location",
		moveLocation					= "Move Location",
		removeLocation					= "Remove Location",
		minimumGP						= "Minimum GP",
		locationEditor					= "Location Editor",
		locationName					= "Location Name",
		gatherUnspoiled					= "Gather Unspoiled",
		minerGearset					= "Miner Gearset",
		botanistGearset					= "Botanist Gearset",
		refreshMap						= "Refresh Map",
		hour							= "Hour",
		class							= "Class",
		isIdle							= "Is Idle",
		objectiveIndex					= "Objective Index",
		stepIndex						= "Step Index",
		killCount					 	= "Kill Count",
		autoEquip					 	= "Auto-Equip",
		idlePulseCount					= "Idle Count",
		taskDelay						= "Task Delay (ms)",
		eorzeaTime						= "Eorzea Time",
		potionHP						= "Potion HP",
		potionMP						= "Potion MP",
		
		teleporter 						= "Teleporter",
		waypoint 						= "Waypoint",
		newWaypoint 					= "New Waypoint",
		editWaypoint					= "Edit Waypoint",
		newName 						= "New Name",
		deleteWaypoint 					= "Delete Waypoint",
		renameWaypoint	 				= "Rename Waypoint",
		getTargetName					= "Get Target Name",
		saveAsTargetPos					= "Save @ Target POS",
		saveAsPlayerPos					= "Save @ Player POS",
		save							= "Save",
		move							= "Move",
		distance						= "Distance",
		
		importExport 					= "Import / Export",
		autoExport						= "Auto Export",
		fileName						= "File Name",
		gatherLocations					= "Gather Locations",
		huntLocations					= "Hunt Locations",
		basicExport						= "Basic Export",
		basicImport						= "Basic Import",
		markerImport					= "Marker Import",
		overwriteExisting				= "Overwrite Existing",
		allMarkers						= "All Markers",
		exportSettings					= "Export Settings",
		importSettings					= "Import Settings",
		exportGlobal					= "Export Global",
		importGlobal					= "Import Global",
		
		minimumCP						= "Minimum CP",
		craftAmount						= "Craft Amount",
		
		--===== Added 1/21/15 - Ace
		paranoid						= "Paranoid",
		permaSwiftcast					= "PermaSwiftCast",
		castPrevention					= "Cast Prevention",
		shortcutManager					= "Shortcut Manager",
		food							= "Food",
		foodHQ							= "Food HQ",
		curielRoot						= "Curiel Root",
		--====== Added 1/22/15 - Ace
		whitelistTarget					= "Whitelist Target",
		validSlots						= "Valid Slots",
		--====== Added 2/15/15 - Ace
		quickStartMode					= "QuickStart",
		--====== Added 2/18/15 - Ace
		totMin							= "ToT >=",
		totMax							= "ToT <",
		htSucceedMax					= "Hasty Touch Success <",
		shStackMin						= "Steady Hand Stack >=",
		manipMax						= "Manipulation Uses <",
		--====== Added 3/13/15 - Ace
		doHuntingLog					= "Do Hunting Log",
		--====== Added 4/2/15 - Ace
		frontlines						= "Frontlines",
		confirm							= "Confirm",
		yes								= "Yes",
		no								= "No",
		debugging						= "Debugging",
		debugItems						= "Debug Items",
		prevComboSkill					= "Previous Combo Skill",
		prevComboSkillNot				= "Previous Combo Skill NOT",
		currentActionNot				= "Current Action NOT",
		filter1							= "Filter 1",
		filter2							= "Filter 2",
		filter3							= "Filter 3",
		filter4							= "Filter 4",
		filter5							= "Filter 5",
		underAttack						= "Under Attack",
		hpAdvantage						= "HP Advantage >=",
		targetTPLE						= "Target TP <=",
		targetMPLE						= "Target MP <=",
		performance						= "Performance",
		loot							= "Loot",
		telecast						= "Telecast",
		need							= "Need",
		greed							= "Greed",
		pass							= "Pass",
		extreme							= "Extreme",
		fast							= "Fast",
		--normal							= "Normal",
		slow							= "Slow",
		shortcut						= "Shortcut",
		modifierKey						= "Modifier Key",
		shortcutKey						= "Shortcut Key",
		waitNearEvac					= "Wait Near Evac",
		randomMovement					= "Randomize Movement",
		--====== Added 6/26/15 - Ace
		underAttackMelee				= "Under Attack (Melee)",
		chain							= "Chain",
		chainStart 						= "Chain Start",
		chainEnd						= "Chain End",
		enmityAOE						= "Enmity AOE",
		frontalCone						= "Frontal Cone",
		tankedTargetsOnly				= "Tanked Targets Only",
		aoeCenter						= "AOE Center",
		comboSkill						= "Combo Skill",
		offGCDSkill						= "Off GCD Skill",
		removesBuff						= "Removes Buff",
		--======= Added 7/6/15 - Ace
		minContentLevel	 				= "Min Content Level",
		maxContentLevel	 				= "Max Content Level",
		maxRadius						= "Max Radius",
		dangerousArea					= "Dangerous Area",
		--======= Added 7/19/15 - Ace
		useChum							= "Use Chum",
		usePatience						= "Use Patience",
		usePatience2					= "Use Patience II",
		moochableFish					= "Moochable Fish",
		whitelistFish					= "Whitelist Fish",
		whitelistFishHQ					= "Whitelist Fish (HQ)",
		blacklistFish					= "Blacklist Fish",
		blacklistFishHQ					= "Blacklist Fish (HQ)",
		singleUse						= "Single Use",
		
		--===== Added 9/20/15 - Sebbs
		maxdurabmin						= "Max Durability >=",
		maxdurabmax						= "Max Durability <",
		maxprogrmin						= "Max Progress >=",
		maxprogrmax						= "Max Progress <",
		
		--===== Added 9/23/15 - Sebbs
		-- Help
		assisthelp						= "Assist Mode will... \
\
You Steer, we Shoot. \
\
Combat routines come from Skill Profile or ACR. \
Combat is only as good as the Profile used.",
		grindhelp						= "Grind Mode will... \
\
Do Fates, Huntlogs and Grind Mobs. \
\
Only for COMBAT Classes. \
\
While we endevour to Automate Settings, \
Settings can be changed if Advanced Settings is enabled. \
\
Combat routines come from Skill Profile or ACR. \
Combat is only as good as the Profile used.",
		gatherhelp						= "Gather Mode will... \
\
Use Markers, Profiles or Quickstart. \
Only for Miner or Botanist. \
\
Skills use are set by Skill Profile",
		fishhelp						= "Fish Mode will... \
\
Use Markers, Profiles or Quickstart. \
\
Only for Fisher. \
\
Skills are NOT set via Skill Profile. \
Set Skills Via Marker or Profiles.",

-- Faq
		assistfaq						= "My Bot Wont attack? \
\
Check your skill profile is set to the right Class/Job. \
Is Start combat Checked?",
		grindfaq						= "My Bot Doesnt move? \
\
Are any valid Fates Available? \
Are Max Fate settings to low? \
\
My Bot Wont attack? \
\
Check your skill profile is set to the right Class/Job.",
		gatherhfaq						= "Bot Doesnt move? \
\
Profile has no valid tasks? \
Markers have radius to small? \
Heavensward or Stormblood may need Marker list.",
		fishfaq						= "Bot Doesnt Fish? \
\
Profile has no valid tasks? \
Current location has Lockout out due to fishing Limit?",
		
	-- Missing GUI strings 09/27/17 HusbandoMax
		-- Shared
		debugLevel = "Debug Level",
		addCollectable = "Add Collectable",
		itemName = "Item Name",
		minValue = "Min Value",
		noProfileSelected = "Please select/create a valid profile.",
		markerMode = "Marker Mode",
		markerType = "Marker Type",
		useCordials = "Use Cordials.",
		collectablePresets = "Use Known Defaults",
		expManuals = "Use Experience Manuals",
		
		-- Assist
		followTarget = "Follow Target",
		faceTarget = "Face Target",
		clientAutoface = "Using Client Autoface",
		-- Craft
		forSingleCraftsOnly = "For Single Crafts Only",
		craftDebug = "Craft Debug",
		useHQMats = "Use HQ Mats",
		onlyIfNecesssary = "Only If Necesssary",
		-- Fish
		fishMarkerProfileMode = "Fish Mode",
		baitType = "Bait Type",
			-- Fish Actions
		mooch = "Mooch",
		mooch2 = "Mooch II",
		patience = "Patience",
		patience2 = "Patience II",
		snagging = "Snagging",
		fishEyes = "Fish Eyes",
		chum = "Chum",
		doubleHook = "Double Hook",
		fishDebug = "Fish Debug",
		-- Gather
		gatherDebug = "Gather Debug",
		gatherMarkerProfileMode = "Gather Mode",
		minGPHighCordial = "Min GP - High Cordial",
		minGPCordial = "Min GP - Cordial",
		minGPWateredCordial = "Min GP - Watered Cordial",
		stealthDetectRange = "Stealth - Detect Range",
		stealthRemoveRange = "Stealth - Remove Range",
		smartStealth = "Smart Stealth",
		gatherSlotQuickstart = "Gather Slot",
		mapsQuickstart = "Maps",
		gardeningQuickstart = "Gardening",
		raresQuickstart = "Rares",
		superRaresQuickstart = "Super Rares",
		chocoboFoodQuickstart = "Chocobo Food",
		-- Grind
		AutoLevelMode = "Auto-Level Mode",
		ModifyAutoGrind = "Modify Auto-Grind",
		DoOnlyFates = "Do Only Fates",
		KillNonFateAggro = "Kill Non-Fate Aggro",
		AdvancedSettings = "Advanced Settings",
		DoLuminous = "Do Luminous",
		FateType = "Fate Type",
		Enable = "Enable",
		Startat = "Start at %%",
		Chain = "Chain",
		Battle = "Battle",
		Boss = "Boss",
		Grind = "Grind",
		Defense = "Defense",
		Escort = "Escort",
		MinFateLv = "Min Fate Lv.",
		SetNoMinFateLevel = "No Min Fate Level",
		MaxFateLv = "Max Fate Lv.",
		SetNoMaxFateLevel = "No Max Fate Level",
		GrindDebug = "Grind Debug",
		-- Mini Games
		CuffaCur = "Cuff-a-Cur",
		MonsterToss = "Monster Toss",
		TowerStriker = "Tower Striker",
		RandomizeGame = "Randomize Game",
		RandomTimeMin = "Random Time Min (m)",
		RandomTimeMax = "Random Time Max (m)",
		PlayTime = "Play Time (m)",
		RestTime = "Rest Time (m)",
		PostGameDelay = "Post-Game Delay (ms)",
		-- Party Grind
		SynctoFates = "Sync to Fates",
		
	-- Tooltips :D 09/27/17 HusbandoMax
		-- Shared
		debugLevelTooltip = "Change the Debug message level. (The higher the number the more detailed the messages)",
		addCollectableTooltip = "Add a new Collectable to the list below.",
		itemNameCollectableTooltip = "Case-sensitive item name for the item to become a collectable.",
		itemRaitingCollectableTooltip = "Minimum collectable value at which the item will be accepted as a collectable.",
		profileTooltip = "The profile to be used in the current mode. (Crafting Orders, Gathering, Fishing)",
		markerModeTooltip = "Select Single,Random or List.",
		markerTypeTooltip = "Marker type to show in the list below.",
		useCordialsTooltip = "Allow use of Cordials for GP.",
		collectablePresetsTooltip = "Add Known Collectables to the list below.",
		-- Assist
		assistTooltip = "None: Use manual targetting.\
Lowest Health: Targets the lowest health target within range.\
Highest Health: Targets the highest health target within range.\
Nearest: Targets the closest target within range.\
Tank Assist: Targets whatever your tank is targetting.",
		assistPriorityTooltip = "Prioritize Damage or Healing.",
		followTargetTooltip = "Attempts to continually follow the target (useful in PvP).",
		faceTargetTooltip = "Attempts to continually face the target.\nWarning:  Dangerous if using Standard movement mode.",
		clientAutofaceTooltip = "This option should be turned on if you are using the game client's [Face Target on Attack] options.",
		startCombatTooltip = "If this option is off, the bot will not attack a mob that is not in combat already.",
		confirmDutyTooltip = "Auto accepts Duty Queue.",
		-- Craft
		craftingOrderEditTooltip = "Opens the Crafting Order Editor.",
		craftingOrderCreateTooltip = "Creates a New Crafting Order profile.",
		expManualsTooltip = "Allow use of Experience boost manuals.",
		craftDebugTooltip = "Enable Debug messages in console.",
		forSingleCraftsOnlyTooltip = "These settings are for Single Craft (When no profile is selected)",
		craftAmountTooltip = "Haw many crafts to complete before stopping.",
		minimumCPTooltip = "CP required before starting the craft. (Useful for CP food)",
		useHQMatsTooltip = "Allow the use of HQ materials while crafting.",
		onlyIfNecesssaryTooltip = "Only use HQ materials if there are no NQ materials left.",
		-- Fish
		fishMarkerProfileModeTooltip = "Select between Markers, Profile or Quickstart.",
		baitTypeTooltip = "Bait to be used in Quick Start mode.",
			-- Fish Actions
		moochTooltip = "Allow fish mooching.",
		mooch2Tooltip = "Allow fish mooching (Mooch 2).",
		patienceTooltip = "Use Patience while fishing.",
		patience2Tooltip = "Use Patience 2 while fishing.",
		snaggingTooltip = "Apply the Snagging buff when fishing.",
		fishEyesTooltip = "Apply the Fish Eyes buff when fishing.",
		chumTooltip = "Use Chum while fishing.",
		doubleHookTooltip = "Use Double Hook.",
		fishDebugTooltip = "Enable Debug messages in console.",
		-- Gather
		gatherDebugTooltip = "Enable Debug messages in console.",
		gatherMarkerProfileModeTooltip = "Select between Markers, Profile or Quickstart.",
		minGPHighCordialTooltip = "Min GP required before using a High Cordial.",
		minGPCordialTooltip = "Min GP required before using a Cordial.",
		minGPWateredCordialTooltip = "Min GP required before using a Watered Cordial.",
		stealthDetectRangeTooltip = "Enemy range before applying Stealth.",
		stealthRemoveRangeTooltip = "Enemy range before removing Stealth.",
		smartStealthTooltip = "Smarter Stealth based on players direction and mob.",
		gatherSlotQuickstartTooltip = "Set the item slot to gather.",
		mapsQuickstartTooltip = "Gather Maps when avalible.",
		gardeningQuickstartTooltip = "Gather Gardening when avalible.",
		raresQuickstartTooltip = "Gather Rares when avalible.",
		superRaresQuickstartTooltip = "Gather Super Rares when avalible.",
		chocoboFoodQuickstartTooltip = "Gather Chocobo Food when avalible.",
		-- Grind
		AutoLevelModeTooltip = "Automatically switch maps to continue leveling in an optimal area.",
		ModifyAutoGrindTooltip = "Opens a GUI to edit the Auto-Level code",
		doFatesTooltip = "When enabled, the bot will complete FATEs in addition to mob-grinding.",
		DoOnlyFatesTooltip = "When enabled, the bot will idle between FATEs, and will not perform mob-grinding.",
		KillNonFateAggroTooltip = "Kills any Non-Fate Aggro",
		AdvancedSettingsTooltip = "Enable use of Advanced Settings",
		DoAtmaTooltip = "Grind Atma crystals and moves to the next zones. (Relic)",
		DoLuminousTooltip = "Grind Luminous crystals and moves to the next zones. (Relic)",
		MinFateLvTooltip = "Number of levels below current Player level.",
		SetNoMinFateLevelTooltip = "Number of levels below current Player level.",
		MaxFateLvTooltip = "Number of levels above current Player level.",
		SetNoMaxFateLevelTooltip = "Number of levels above current Player level.",
		fateTeleportPercentTooltip = "Fate percentage required before teleporting to it. (Hacks)",
		restInFatesTooltip = "Allow resting while in fate when low HP.",
		waitNearEvacTooltip = "Allow wating near evac postions instead of standing where you are waiting.",
		GrindDebugTooltip = "Enable Debug messages in console.",
		prioritizeClaimsTooltip = "Will claim all mobs withing set range on you for optimal drops.",
		claimRangeTooltip = "Range to claim when using Prioritize Claims.",
		attackClaimedTooltip = "Attack already clamied mobs.",
		doHuntingLogTooltip = "When enabled, FFXIVMinion will complete your class hunting log while grinding.",
		-- Mini Games
		CuffaCurTooltip = "Play the Cuff-a-Cur mingame.",
		MonsterTossTooltip = "Play the Monster Toss mingame.",
		TowerStrikerTooltip = "Play the Tower Striker mingame.",
		RandomizeGameTooltip = "Changed to a random minigame. (Time set with Random Time Min/Max)",
		RandomTimeMinTooltip = "Min time used when randomly changing minigames.",
		RandomTimeMaxTooltip = "Max time used when randomly changing minigames.",
		PlayTimeTooltip = "Time to play before resting.",
		RestTimeTooltip = "Time to rest after playing before starting again.",
		PostGameDelayTooltip = "Delay between starting each minigame.",
		-- Party Grind
		UseGamePartyLeaderTooltip = "Use your current party leader as the person to follow/assist.",
		SynctoFatesTooltip = "Will automatically Sync to Fates when withing a fate zone.",
		PartyLeaderTooltip = "Enter a players name to follow/assist them.",
		GetPartyLeaderTooltip = "Gets your current targets name and inserts it above.",
		
		
		--us end
    },         
	
    
    
    
	
}

-- merge the ml_strings into the miniondbstrings, so they get all translated
for language,data in pairs(ml_strings) do
	for skey,str in pairs(data) do
		if ( ml_miniondbstrings[skey] == nil ) then
			ml_miniondbstrings[skey] = { [language] = str }
			
		else
			if ( ml_miniondbstrings[skey][language] == nil ) then
				ml_miniondbstrings[skey][language] = str
			end
		end
	end	
end
-- merge  the minionlib strings with our ffxiv strings
for language,data in pairs(ffxiv_strings) do
	if ( ml_strings[language] ) then
		for skey,str in pairs(data) do
			if ( ml_strings[language][skey] == nil ) then
				ml_strings[language][skey] = str
			else
				--d("Not adding dupliocate string :"..skey)
			end
		end
	end
	
	-- add them to the new ml_miniondbstrings as well
	for skey,str in pairs(data) do
		if ( ml_miniondbstrings[skey] == nil ) then
			ml_miniondbstrings[skey] = { [language] = str }
			
		else
			if ( ml_miniondbstrings[skey][language] == nil ) then
				ml_miniondbstrings[skey][language] = str
			end
		end
	end	
end

function GetUSString(stringName)
	return GetStringByLang(stringName,"en")
end