-- Persistent Data
local multiRefObjects = {

} -- multiRefObjects
local obj1 = {
	["skills"] = {
		[1] = {
			["alias"] = "";
			["condition"] = "NotUsed";
			["cpbuff"] = "";
			["cpmax"] = 0;
			["cpmin"] = 0;
			["cpnbuff"] = "253+262";
			["durabmax"] = 0;
			["durabmin"] = 0;
			["htsucceed"] = 0;
			["id"] = 281;
			["iqstack"] = 0;
			["lastcast"] = 0;
			["manipmax"] = 0;
			["name"] = "Steady Hand II";
			["prio"] = 1;
			["progrmax"] = 0;
			["progrmin"] = 0;
			["qualitymax"] = 0;
			["qualitymaxper"] = 0;
			["qualitymin"] = 0;
			["qualityminper"] = 0;
			["shstackmin"] = 0;
			["stepmax"] = 0;
			["stepmin"] = 0;
			["totmax"] = 0;
			["totmin"] = 0;
			["type"] = 1;
			["used"] = "1";
		};
		[2] = {
			["alias"] = "";
			["condition"] = "NotUsed";
			["cpbuff"] = "";
			["cpmax"] = 0;
			["cpmin"] = 0;
			["cpnbuff"] = "256";
			["durabmax"] = 0;
			["durabmin"] = 0;
			["htsucceed"] = 0;
			["id"] = 283;
			["iqstack"] = 0;
			["lastcast"] = 0;
			["manipmax"] = 0;
			["name"] = "Ingenuity II";
			["prio"] = 2;
			["progrmax"] = 0;
			["progrmin"] = 0;
			["qualitymax"] = 0;
			["qualitymaxper"] = 0;
			["qualitymin"] = 0;
			["qualityminper"] = 0;
			["shstackmin"] = 0;
			["stepmax"] = 0;
			["stepmin"] = 0;
			["totmax"] = 0;
			["totmin"] = 0;
			["type"] = 1;
			["used"] = "1";
		};
		[3] = {
			["alias"] = "";
			["condition"] = "NotUsed";
			["cpbuff"] = "";
			["cpmax"] = 0;
			["cpmin"] = 0;
			["cpnbuff"] = "";
			["durabmax"] = 0;
			["durabmin"] = 0;
			["htsucceed"] = 0;
			["id"] = 100021;
			["iqstack"] = 0;
			["lastcast"] = 0;
			["manipmax"] = 0;
			["name"] = "Standard Synthesis";
			["prio"] = 3;
			["progrmax"] = 0;
			["progrmin"] = 0;
			["qualitymax"] = 0;
			["qualitymaxper"] = 0;
			["qualitymin"] = 0;
			["qualityminper"] = 0;
			["shstackmin"] = 0;
			["stepmax"] = 0;
			["stepmin"] = 0;
			["totmax"] = 0;
			["totmin"] = 0;
			["type"] = 1;
			["used"] = "1";
		};
	};
	["version"] = 2;
}
return obj1
